In [91]:
import pandas as pd
import numpy as py
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

In [92]:
dataset = pd.read_csv('news.csv', index_col=None)

In [93]:
dataset = dataset.drop('Unnamed: 0', axis=1)
dataset

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL


In [94]:
dataset['label'].value_counts

<bound method IndexOpsMixin.value_counts of 0       FAKE
1       FAKE
2       REAL
3       FAKE
4       REAL
        ... 
6330    REAL
6331    FAKE
6332    FAKE
6333    REAL
6334    REAL
Name: label, Length: 6335, dtype: object>

In [95]:
indep = dataset['text']
dep = dataset['label']

In [96]:
indep

0       Daniel Greenfield, a Shillman Journalism Fello...
1       Google Pinterest Digg Linkedin Reddit Stumbleu...
2       U.S. Secretary of State John F. Kerry said Mon...
3       — Kaydee King (@KaydeeKing) November 9, 2016 T...
4       It's primary day in New York and front-runners...
                              ...                        
6330    The State Department told the Republican Natio...
6331    The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332     Anti-Trump Protesters Are Tools of the Oligar...
6333    ADDIS ABABA, Ethiopia —President Obama convene...
6334    Jeb Bush Is Suddenly Attacking Trump. Here's W...
Name: text, Length: 6335, dtype: object

In [97]:
dep

0       FAKE
1       FAKE
2       REAL
3       FAKE
4       REAL
        ... 
6330    REAL
6331    FAKE
6332    FAKE
6333    REAL
6334    REAL
Name: label, Length: 6335, dtype: object

In [98]:
X_train,X_test,y_train,y_test = train_test_split(indep,dep,test_size=0.30,random_state=53)

In [99]:
countvector = CountVectorizer(stop_words="english")
count_train = countvector.fit_transform(X_train)
print(count_train)
count_test = countvector.transform(X_test)

  (0, 11291)	1
  (0, 14397)	3
  (0, 46000)	1
  (0, 29899)	1
  (0, 23666)	1
  (0, 42735)	4
  (0, 28294)	2
  (0, 46051)	1
  (0, 45333)	1
  (0, 36607)	1
  (0, 30207)	1
  (0, 19536)	3
  (0, 15302)	2
  (0, 27653)	1
  (0, 11228)	2
  (0, 8815)	2
  (0, 47576)	1
  (0, 35601)	1
  (0, 24408)	1
  (0, 10708)	4
  (0, 24349)	2
  (0, 47143)	1
  (0, 52803)	1
  (0, 16125)	2
  (0, 52745)	5
  :	:
  (4433, 54901)	1
  (4433, 35836)	1
  (4433, 53806)	1
  (4433, 51202)	1
  (4433, 13166)	1
  (4433, 11604)	1
  (4433, 56145)	1
  (4433, 36356)	1
  (4433, 42811)	1
  (4433, 7681)	1
  (4433, 3366)	1
  (4433, 43287)	1
  (4433, 48275)	1
  (4433, 42762)	1
  (4433, 7675)	1
  (4433, 22784)	1
  (4433, 7232)	1
  (4433, 50866)	1
  (4433, 39480)	1
  (4433, 17522)	1
  (4433, 50865)	1
  (4433, 11444)	1
  (4433, 53817)	1
  (4433, 21229)	1
  (4433, 8102)	1


In [100]:
#Naive bayes

classifier = MultinomialNB()
classifier.fit(count_train, y_train)

y_predict = classifier.predict(count_test)

accuracyScore = accuracy_score(y_test,y_predict)
confusionMatrix = confusion_matrix(y_test,y_predict,labels=['FAKE','REAL'])

In [101]:
accuracyScore

0.9021567596002105

In [102]:
confusionMatrix

array([[794, 119],
       [ 67, 921]], dtype=int64)

In [103]:
classificationReport = classification_report(y_test,y_predict)
print(classificationReport)

              precision    recall  f1-score   support

        FAKE       0.92      0.87      0.90       913
        REAL       0.89      0.93      0.91       988

    accuracy                           0.90      1901
   macro avg       0.90      0.90      0.90      1901
weighted avg       0.90      0.90      0.90      1901



In [104]:
dataset['text'][0]

'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe FBI’s leadership is being warned that the entir

In [105]:
count_train[[0]]

<1x57870 sparse matrix of type '<class 'numpy.int64'>'
	with 156 stored elements in Compressed Sparse Row format>

In [106]:
X_train[[0]]

0    Daniel Greenfield, a Shillman Journalism Fello...
Name: text, dtype: object

In [107]:
classifier.predict(count_test[[0]])

array(['REAL'], dtype='<U4')

In [108]:
# Passive Aggresive Classifier

classifier_1 = PassiveAggressiveClassifier(C=1.0, fit_intercept=True, n_jobs=None, random_state=0)
classifier_1.fit(count_train, y_train)

y_predict_1 = classifier_1.predict(count_test)

accuracyScore_1 = accuracy_score(y_test,y_predict_1)
confusionMatrix_1 = confusion_matrix(y_test,y_predict_1,labels=['FAKE','REAL'])
classificationReport_1 = classification_report(y_test,y_predict_1)

In [109]:
accuracyScore_1

0.8958442924776433

In [110]:
confusionMatrix_1

array([[821,  92],
       [106, 882]], dtype=int64)

In [111]:
print(classificationReport_1)

              precision    recall  f1-score   support

        FAKE       0.89      0.90      0.89       913
        REAL       0.91      0.89      0.90       988

    accuracy                           0.90      1901
   macro avg       0.90      0.90      0.90      1901
weighted avg       0.90      0.90      0.90      1901



In [112]:
# SVC

classifier_2 = SVC(kernel='linear',C=1.0)
classifier_2.fit(count_train, y_train)

y_predict_2 = classifier_2.predict(count_test)

accuracyScore_2 = accuracy_score(y_test,y_predict_2)
confusionMatrix_2 = confusion_matrix(y_test,y_predict_2,labels=['FAKE','REAL'])
classificationReport_2 = classification_report(y_test,y_predict_2)

In [113]:
accuracyScore_2

0.8679642293529721

In [114]:
confusionMatrix_2

array([[807, 106],
       [145, 843]], dtype=int64)

In [115]:
print(classificationReport_2)

              precision    recall  f1-score   support

        FAKE       0.85      0.88      0.87       913
        REAL       0.89      0.85      0.87       988

    accuracy                           0.87      1901
   macro avg       0.87      0.87      0.87      1901
weighted avg       0.87      0.87      0.87      1901



In [116]:
#Logistic Regression

classifier_3 = LogisticRegression(random_state=0)
classifier_3.fit(count_train, y_train)

y_predict_3 = classifier_3.predict(count_test)

accuracyScore_3 = accuracy_score(y_test,y_predict_3)
confusionMatrix_3 = confusion_matrix(y_test,y_predict_3,labels=['FAKE','REAL'])
classificationReport_3 = classification_report(y_test,y_predict_3)

C:\Users\HP\anaconda3\envs\aiml\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [117]:
accuracyScore_3

0.9210941609679116

In [118]:
confusionMatrix_3

array([[864,  49],
       [101, 887]], dtype=int64)

In [119]:
print(classificationReport_3)

              precision    recall  f1-score   support

        FAKE       0.90      0.95      0.92       913
        REAL       0.95      0.90      0.92       988

    accuracy                           0.92      1901
   macro avg       0.92      0.92      0.92      1901
weighted avg       0.92      0.92      0.92      1901



In [120]:
#KNN

classifier_4 = KNeighborsClassifier(n_neighbors = 7, metric='minkowski', p = 2)
classifier_4.fit(count_train, y_train)

y_predict_4 = classifier_4.predict(count_test)

accuracyScore_4 = accuracy_score(y_test,y_predict_4)
confusionMatrix_4 = confusion_matrix(y_test,y_predict_4,labels=['FAKE','REAL'])
classificationReport_4 = classification_report(y_test,y_predict_4)

In [121]:
accuracyScore_4

0.7922146238821672

In [122]:
confusionMatrix_4

array([[758, 155],
       [240, 748]], dtype=int64)

In [123]:
print(classificationReport_4)

              precision    recall  f1-score   support

        FAKE       0.76      0.83      0.79       913
        REAL       0.83      0.76      0.79       988

    accuracy                           0.79      1901
   macro avg       0.79      0.79      0.79      1901
weighted avg       0.80      0.79      0.79      1901



In [130]:
#Decission Tree
classifier_5 = DecisionTreeClassifier(criterion='gini',splitter='best')
classifier_5.fit(count_train, y_train)

y_predict_5 = classifier_5.predict(count_test)

accuracyScore_5 = accuracy_score(y_test,y_predict_5)
confusionMatrix_5 = confusion_matrix(y_test,y_predict_5,labels=['FAKE','REAL'])
classificationReport_5 = classification_report(y_test,y_predict_5)

In [131]:
accuracyScore_5

0.8200946870068385

In [132]:
confusionMatrix_5

array([[764, 149],
       [193, 795]], dtype=int64)

In [133]:
print(classificationReport_5)

              precision    recall  f1-score   support

        FAKE       0.80      0.84      0.82       913
        REAL       0.84      0.80      0.82       988

    accuracy                           0.82      1901
   macro avg       0.82      0.82      0.82      1901
weighted avg       0.82      0.82      0.82      1901



In [134]:
#Random Forest
classifier_6 = RandomForestClassifier(n_estimators=100,criterion='gini',random_state=0)
classifier_6.fit(count_train, y_train)

y_predict_6 = classifier_6.predict(count_test)

accuracyScore_6 = accuracy_score(y_test,y_predict_6)
confusionMatrix_6 = confusion_matrix(y_test,y_predict_6,labels=['FAKE','REAL'])
classificationReport_6 = classification_report(y_test,y_predict_6)

C:\Users\HP\anaconda3\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\HP\anaconda3\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):


In [135]:
accuracyScore_6

0.9037348763808521

In [136]:
confusionMatrix_6

array([[829,  84],
       [ 99, 889]], dtype=int64)

In [137]:
print(classificationReport_6)

              precision    recall  f1-score   support

        FAKE       0.89      0.91      0.90       913
        REAL       0.91      0.90      0.91       988

    accuracy                           0.90      1901
   macro avg       0.90      0.90      0.90      1901
weighted avg       0.90      0.90      0.90      1901

